import { Locale } from '@/types';

export const SUPPORTED_LANGS: Locale[] = ['en', 'it', 'ru'];
export const DEFAULT_LANG: Locale = 'en';

export const LOCALES: Record<Locale, string> = {
  en: 'en-US',
  it: 'it-IT',
  ru: 'ru-RU',
};

export const LANG_LABELS: Record<Locale, string> = {
  en: 'English',
  it: 'Italiano',
  ru: 'Русский',
};

export const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    'enter.text': 'Click to Enter',
    'help.title': 'Quick guide',
    'help.aria': 'Quick guide',
    'lang.aria': 'Language',
    'volume.aria': 'Music volume',
    'volume.slider': 'Volume',
    'avatar.changeTitle': 'Change profile photo',
    'avatar.change': 'Change',
    'bio': 'Junior Web Developer | Gamer | Platinum+ Optimizer Web Dev',
    'live.aria': 'Watch the live stream',
    'live.titleDefault': 'Live right now',
    'live.subDefault': 'Click to join',
    'live.cta': 'Watch →',
    'live.watchAria': 'Watch the stream on {platform}: {title}',
    'live.viaDiscord': 'Via Discord',
    'live.manualStream': 'Manual stream',
    'live.onTwitch': 'Live on Twitch',
    'live.onYoutube': 'Live on YouTube',
    'live.onKick': 'Live on Kick',
    'live.activeStream': 'Stream active',
    'live.streaming': 'Streaming',
    'visitor.kicker': 'Unique visitors',
    'visitor.subDefault': 'Real-time count',
    'visitor.badgeLive': 'Live',
    'visitor.badgeSetup': 'Setup',
    'visitor.badgeOffline': 'Offline',
    'visitor.labelOne': '1 person has visited the site',
    'visitor.labelMany': '{count} people have visited the site',
    'visitor.error.kv': 'Connect KV VISITOR_STORE on Cloudflare Pages',
    'visitor.error.apiOk': 'API ok but visitors not responding — check KV',
    'visitor.error.deploy': 'Upload _routes.json + functions/ and redeploy on Cloudflare',
    'visitor.error.kvBinding': 'Cloudflare: add KV binding → VISITOR_STORE',
    'visitor.error.apiActive': 'API active — connect KV VISITOR_STORE on Cloudflare',
    'visitor.error.apiInactive': 'API inactive: upload _routes.json and redeploy',
    'visitor.error.unavailable': 'Counter temporarily unavailable',
    'discord.statusTitle': 'Discord status',
    'discord.connecting': 'Connecting to Discord…',
    'discord.showProfile': 'Show Discord profile',
    'discord.hideProfile': 'Hide Discord profile',
    'discord.addFriend': 'Add me as a friend',
    'discord.badgesAria': 'Discord profile badges',
    'discord.badgesUnavailable': 'Badges unavailable',
    'discord.noBadges': 'No public badges on this profile',
    'discord.connectLanyardBadges': 'Connect Lanyard to see badges',
    'discord.notOnDiscord': 'Not connected to Discord',
    'discord.noActivity': 'No activity in progress',
    'discord.listeningSpotify': 'Listening on Spotify',
    'discord.live': 'Streaming',
    'discord.playingGame': 'Playing a game',
    'discord.customStatus': 'Custom status',
    'discord.statusSuffix': ' · STATUS',
    'discord.lanyardLabel': 'LANYARD',
    'discord.lanyardActivate': 'Enable Lanyard on Discord',
    'discord.lanyardInstall': 'Install the Lanyard app and open Discord',
    'discord.lanyardError': 'Unable to reach Lanyard',
    'discord.lanyardErrorSub': 'Check your connection',
    'discord.status.online': 'ONLINE',
    'discord.status.idle': 'IDLE',
    'discord.status.dnd': 'DO NOT DISTURB',
    'discord.status.offline': 'OFFLINE',
    'music.loading': 'Loading…',
    'music.fromYoutube': 'Audio from YouTube',
    'music.youtubeBrand': 'YouTube',
    'music.error': 'Could not load YouTube player',
    'music.prev': 'Previous track',
    'music.next': 'Next track',
    'music.play': 'Play',
    'music.pause': 'Pause',
    'music.progress': 'Song progress',
    'social.twitter': 'X / Twitter',
    'social.telegram': 'Platinum+ Optimizer',
    'social.gmail': 'Contact Me',
    'social.github': 'Repo',
    'social.kofi': 'Donations',
    'social.kofi.warning': 'Warning: No payment methods are currently connected to Ko-fi.',
    'social.kofi.visit': 'Visit Ko-fi',
    'crop.title': 'Resize your photo',
    'crop.hint': 'Drag to move · Scroll / pinch to zoom',
    'crop.zoom': 'Zoom',
    'crop.cancel': 'Cancel',
    'crop.confirm': 'Confirm',
    'tutorial.kicker': 'Quick guide',
    'tutorial.step': 'Step {n} of {total}',
    'tutorial.skip': 'Skip guide',
    'tutorial.back': 'Back',
    'tutorial.next': 'Next',
    'tutorial.finish': 'Start exploring',
    'tutorial.step1.title': 'What is this page?',
    'tutorial.step1.body': "You found IL DENTE PROIBITO's personal page — not a shop, forum, or app to download. It's a digital business card: one link to discover who's behind it, what they do (web development, gaming, optimization), and where to follow them online.",
    'tutorial.step2.title': 'Choose your language',
    'tutorial.step2.body': 'Use the globe selector top-left to switch between English, Italian, and Russian anytime. The entire site updates instantly — try it here or on the corner selector.',
    'tutorial.step3.title': 'Music & atmosphere',
    'tutorial.step3.body': 'Click "Click to Enter" to unlock background music. Top-right: volume control. On the card: play/pause, skip tracks, and scrub the playlist — no external apps needed.',
    'tutorial.step4.title': "Who's online right now",
    'tutorial.step4.body': "The Discord card shows in real time whether IL DENTE PROIBITO is online, offline, or away, and what they're doing (game, Spotify, etc.). When streaming on Twitch, a red \"LIVE\" banner appears. The visitor counter shows how many unique people have stopped by.",
    'tutorial.step5.title': 'Connect & interact',
    'tutorial.step5.body': 'The icons at the bottom link to X (Twitter), Telegram (Platinum+ Optimizer group), Gmail (ildenteproibito@gmail.com), and GitHub (site source code). You can change the profile photo by clicking the avatar (once only) and add them on Discord via "Show Discord profile" → "Add me as a friend".',
    'elapsed.h': '{h}h {m}m elapsed',
    'elapsed.m': '{m}m {s}s elapsed',
    'elapsed.s': '{s}s elapsed',
    'ui.toggle': 'Toggle UI visibility',
  },
  it: {
    'enter.text': 'Clicca per entrare',
    'help.title': 'Guida rapida',
    'help.aria': 'Guida rapida',
    'lang.aria': 'Lingua',
    'volume.aria': 'Volume musica',
    'volume.slider': 'Volume',
    'avatar.changeTitle': 'Cambia foto profilo',
    'avatar.change': 'Cambia',
    'bio': 'Junior Web Developer | Gamer | Platinum+ Optimizer Web Dev',
    'live.aria': 'Guarda la diretta live',
    'live.titleDefault': 'In diretta adesso',
    'live.subDefault': 'Clicca per entrare',
    'live.cta': 'Guarda →',
    'live.watchAria': 'Guarda la diretta su {platform}: {title}',
    'live.viaDiscord': 'Tramite Discord',
    'live.manualStream': 'Stream manuale',
    'live.onTwitch': 'In diretta su Twitch',
    'live.onYoutube': 'In diretta su YouTube',
    'live.onKick': 'In diretta su Kick',
    'live.activeStream': 'Stream attivo',
    'live.streaming': 'In diretta',
    'visitor.kicker': 'Visitatori unici',
    'visitor.subDefault': 'Conteggio in tempo reale',
    'visitor.badgeLive': 'Live',
    'visitor.badgeSetup': 'Setup',
    'visitor.badgeOffline': 'Offline',
    'visitor.labelOne': '1 persona ha visitato il sito',
    'visitor.labelMany': '{count} persone hanno visitato il sito',
    'visitor.error.kv': 'Collega KV VISITOR_STORE su Cloudflare Pages',
    'visitor.error.apiOk': 'API ok ma visitors non risponde — controlla KV',
    'visitor.error.deploy': 'Carica _routes.json + functions/ e rideploya su Cloudflare',
    'visitor.error.kvBinding': 'Cloudflare: aggiungi binding KV → VISITOR_STORE',
    'visitor.error.apiActive': 'API attiva — collega KV VISITOR_STORE su Cloudflare',
    'visitor.error.apiInactive': 'API non attiva: carica _routes.json e rideploya',
    'visitor.error.unavailable': 'Contatore temporaneamente non disponibile',
    'discord.statusTitle': 'Stato Discord',
    'discord.connecting': 'Connessione a Discord…',
    'discord.showProfile': 'Mostra profilo Discord',
    'discord.hideProfile': 'Nascondi profilo Discord',
    'discord.addFriend': 'Aggiungimi agli amici',
    'discord.badgesAria': 'Badge profilo Discord',
    'discord.badgesUnavailable': 'Badge non disponibili',
    'discord.noBadges': 'Nessun badge pubblico su questo profilo',
    'discord.connectLanyardBadges': 'Collega Lanyard per vedere i badge',
    'discord.notOnDiscord': 'Non connesso a Discord',
    'discord.noActivity': 'Nessuna attività in corso',
    'discord.listeningSpotify': 'In ascolto su Spotify',
    'discord.live': 'In diretta',
    'discord.playingGame': 'Sta giocando',
    'discord.customStatus': 'Stato personalizzato',
    'discord.statusSuffix': ' · STATO',
    'discord.lanyardLabel': 'LANYARD',
    'discord.lanyardActivate': 'Attiva Lanyard su Discord',
    'discord.lanyardInstall': "Installa l'app Lanyard e avvia Discord",
    'discord.lanyardError': 'Impossibile raggiungere Lanyard',
    'discord.lanyardErrorSub': 'Controlla la connessione',
    'discord.status.online': 'ONLINE',
    'discord.status.idle': 'INATTIVO',
    'discord.status.dnd': 'NON DISTURBARE',
    'discord.status.offline': 'OFFLINE',
    'music.loading': 'Caricamento…',
    'music.fromYoutube': 'Audio da YouTube',
    'music.youtubeBrand': 'YouTube',
    'music.error': 'Impossibile caricare il player YouTube',
    'music.prev': 'Brano precedente',
    'music.next': 'Brano successivo',
    'music.play': 'Riproduci',
    'music.pause': 'Pausa',
    'music.progress': 'Avanzamento brano',
    'social.twitter': 'X / Twitter',
    'social.telegram': 'Platinum+ Optimizer',
    'social.gmail': 'Contattami',
    'social.github': 'Repo',
    'social.kofi': 'Donazioni',
    'social.kofi.warning': 'Attenzione: attualmente non ho metodi di pagamento collegati al Ko-fi.',
    'social.kofi.visit': 'Visita Ko-fi',
    'crop.title': 'Ridimensiona la tua foto',
    'crop.hint': 'Trascina per spostare · Scorri / pizzica per zoomare',
    'crop.zoom': 'Zoom',
    'crop.cancel': 'Annulla',
    'crop.confirm': 'Conferma',
    'tutorial.kicker': 'Guida rapida',
    'tutorial.step': 'Step {n} di {total}',
    'tutorial.skip': 'Salta guida',
    'tutorial.back': 'Indietro',
    'tutorial.next': 'Avanti',
    'tutorial.finish': 'Inizia a esplorare',
    'tutorial.step1.title': "Cos'è questa pagina?",
    'tutorial.step1.body': "Hai trovato la pagina personale di IL DENTE PROIBITO — non è un negozio, un forum né un'app da scaricare. È un biglietto da visita digitale: un unico link dove scopri chi c'è dietro, cosa fa (sviluppo web, gaming, ottimizzazione) e dove seguirlo online.",
    'tutorial.step2.title': 'Scegli la lingua',
    'tutorial.step2.body': 'Usa il selettore con il globo in alto a sinistra per passare tra inglese, italiano e russo in qualsiasi momento. Tutto il sito si aggiorna subito — prova qui sotto o sul selettore nell\'angolo.',
    'tutorial.step3.title': 'Musica e atmosfera',
    'tutorial.step3.body': 'Clicca «Clicca per entrare» per sbloccare la musica di sottofondo. In alto a destra: controllo volume. Sulla card: play/pausa, brani avanti/indietro e barra di avanzamento — senza app esterne.',
    'tutorial.step4.title': "Chi c'è online adesso",
    'tutorial.step4.body': 'La scheda Discord mostra in tempo reale se IL DENTE PROIBITO è online, offline o in pausa, e cosa sta facendo (gioco, Spotify, ecc.). Se è in diretta su Twitch compare un banner rosso «LIVE». Il contatore visitatori indica quante persone uniche sono passate di qua.',
    'tutorial.step5.title': 'Collegati e interagisci',
    'tutorial.step5.body': "Le icone in basso portano a X (Twitter), Telegram (gruppo Platinum+ Optimizer), Gmail (ildenteproibito@gmail.com) e GitHub (codice sorgente del sito). Puoi cambiare la foto profilo cliccando sull'avatar (una volta sola) e aggiungerlo su Discord con «Mostra profilo Discord» → «Aggiungimi agli amici».",
    'elapsed.h': '{h}h {m}m trascorsi',
    'elapsed.m': '{m}m {s}s trascorsi',
    'elapsed.s': '{s}s trascorsi',
    'ui.toggle': 'Mostra/Nascondi interfaccia',
  },
  ru: {
    'enter.text': 'Нажмите, чтобы войти',
    'help.title': 'Краткое руководство',
    'help.aria': 'Краткое руководство',
    'lang.aria': 'Язык',
    'volume.aria': 'Громкость музыки',
    'volume.slider': 'Громкость',
    'avatar.changeTitle': 'Сменить фото профиля',
    'avatar.change': 'Сменить',
    'bio': 'Junior Web Developer | Gamer | Platinum+ Optimizer Web Dev',
    'live.aria': 'Смотреть прямой эфир',
    'live.titleDefault': 'В эфире сейчас',
    'live.subDefault': 'Нажмите, чтобы войти',
    'live.cta': 'Смотреть →',
    'live.watchAria': 'Смотреть трансляцию на {platform}: {title}',
    'live.viaDiscord': 'Через Discord',
    'live.manualStream': 'Ручной стрим',
    'live.onTwitch': 'В эфире на Twitch',
    'live.onYoutube': 'В эфире на YouTube',
    'live.onKick': 'В эфире на Kick',
    'live.activeStream': 'Стрим активен',
    'live.streaming': 'В эфире',
    'visitor.kicker': 'Уникальные посетители',
    'visitor.subDefault': 'Подсчёт в реальном времени',
    'visitor.badgeLive': 'Live',
    'visitor.badgeSetup': 'Setup',
    'visitor.badgeOffline': 'Offline',
    'visitor.labelOne': '1 человек посетил сайт',
    'visitor.labelMany': '{count} человек посетили сайт',
    'visitor.error.kv': 'Подключите KV VISITOR_STORE на Cloudflare Pages',
    'visitor.error.apiOk': 'API работает, но visitors не отвечает — проверьте KV',
    'visitor.error.deploy': 'Загрузите _routes.json + functions/ и передеплойте на Cloudflare',
    'visitor.error.kvBinding': 'Cloudflare: добавьте binding KV → VISITOR_STORE',
    'visitor.error.apiActive': 'API активна — подключите KV VISITOR_STORE на Cloudflare',
    'visitor.error.apiInactive': 'API неактивна: загрузите _routes.json и передеплойте',
    'visitor.error.unavailable': 'Счётчик временно недоступен',
    'discord.statusTitle': 'Статус Discord',
    'discord.connecting': 'Подключение к Discord…',
    'discord.showProfile': 'Показать профиль Discord',
    'discord.hideProfile': 'Скрыть профиль Discord',
    'discord.addFriend': 'Добавить в друзья',
    'discord.badgesAria': 'Значки профиля Discord',
    'discord.badgesUnavailable': 'Значки недоступны',
    'discord.noBadges': 'Нет публичных значков в этом профиле',
    'discord.connectLanyardBadges': 'Подключите Lanyard, чтобы видеть значки',
    'discord.notOnDiscord': 'Не подключён к Discord',
    'discord.noActivity': 'Нет активности',
    'discord.listeningSpotify': 'Слушает Spotify',
    'discord.live': 'В эфире',
    'discord.playingGame': 'Играет в игру',
    'discord.customStatus': 'Пользовательский статус',
    'discord.statusSuffix': ' · СТАТУС',
    'discord.lanyardLabel': 'LANYARD',
    'discord.lanyardActivate': 'Включите Lanyard в Discord',
    'discord.lanyardInstall': 'Установите приложение Lanyard и откройте Discord',
    'discord.lanyardError': 'Не удалось подключиться к Lanyard',
    'discord.lanyardErrorSub': 'Проверить соединение',
    'discord.status.online': 'В СЕТИ',
    'discord.status.idle': 'НЕ АКТИВЕН',
    'discord.status.dnd': 'НЕ БЕСПОКОИТЬ',
    'discord.status.offline': 'НЕ В СЕТИ',
    'music.loading': 'Загрузка…',
    'music.fromYoutube': 'Аудио с YouTube',
    'music.youtubeBrand': 'YouTube',
    'music.error': 'Не удалось загрузить плеер YouTube',
    'music.prev': 'Предыдущий трек',
    'music.next': 'Следующий трек',
    'music.play': 'Воспроизвести',
    'music.pause': 'Пауза',
    'music.progress': 'Прогресс трека',
    'social.twitter': 'X / Twitter',
    'social.telegram': 'Platinum+ Optimizer',
    'social.gmail': 'Свяжитесь со мной',
    'social.github': 'Repo',
    'social.kofi': 'Пожертвования',
    'social.kofi.warning': 'Внимание: в настоящее время к Ko-fi не подключены способы оплаты.',
    'social.kofi.visit': 'Перейти на Ko-fi',
    'crop.title': 'Изменить размер фото',
    'crop.hint': 'Перетащите · Прокрутка / щипок для масштаба',
    'crop.zoom': 'Масштаб',
    'crop.cancel': 'Отмена',
    'crop.confirm': 'Подтвердить',
    'tutorial.kicker': 'Краткое руководство',
    'tutorial.step': 'Шаг {n} из {total}',
    'tutorial.skip': 'Пропустить',
    'tutorial.back': 'Назад',
    'tutorial.next': 'Далее',
    'tutorial.finish': 'Начать',
    'tutorial.step1.title': 'Что это за страница?',
    'tutorial.step1.body': 'Вы нашли личную страницу IL DENTE PROIBITO — это не магазин, форум и не приложение для скачивания. Это цифровая визитка: одна ссылка, где можно узнать, кто стоит за проектом, чем занимается (веб-разработка, гейминг, оптимизация) и где следить за ним в сети.',
    'tutorial.step2.title': 'Выберите язык',
    'tutorial.step2.body': 'Используйте селектор с глобусом слева вверху, чтобы переключаться между английским, итальянским и русским в любой момент. Весь сайт обновляется мгновенно — попробуйте здесь или на селекторе в углу.',
    'tutorial.step3.title': 'Музыка и атмосфера',
    'tutorial.step3.body': 'Нажмите «Нажмите, чтобы войти», чтобы включить фоновую музыку. Справа вверху — громкость. На карточке: play/pause, переключение треков и полоса прогресса — без внешних приложений.',
    'tutorial.step4.title': 'Кто онлайн сейчас',
    'tutorial.step4.body': 'Карточка Discord показывает в реальном времени, онлайн ли IL DENTE PROIBITO, офлайн или отошёл, и чем занят (игра, Spotify и т.д.). При трансляции на Twitch появляется красный баннер «LIVE». Счётчик посетителей показывает, сколько уникальных людей заходило на сайт.',
    'tutorial.step5.title': 'Связаться и взаимодействовать',
    'tutorial.step5.body': 'Иконки внизу ведут на X (Twitter), Telegram (группа Platinum+ Optimizer), Gmail (ildenteproibito@gmail.com) и GitHub (исходный код сайта). Можно сменить фото профиля, нажав на аватар (только один раз), и добавить в друзья в Discord через «Показать профиль Discord» → «Добавить в друзья».',
    'elapsed.h': '{h}ч {m}м прошло',
    'elapsed.m': '{m}м {s}с прошло',
    'elapsed.s': '{s}s прошло',
    'ui.toggle': 'Показать/Скрыть интерфейс',
  },
};

export function t(key: string, lang: Locale, vars?: Record<string, string | number>): string {
  let str = STRINGS[lang]?.[key] ?? STRINGS[DEFAULT_LANG][key] ?? key;
  if (vars) {
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
    });
  }
  return str;
}

export function detectLang(): Locale {
  if (typeof window === 'undefined') return DEFAULT_LANG;
  try {
    const saved = localStorage.getItem('site_lang') as Locale;
    if (saved && SUPPORTED_LANGS.includes(saved)) return saved;
  } catch {}
  const browser = (navigator.language || 'en').slice(0, 2).toLowerCase() as Locale;
  return SUPPORTED_LANGS.includes(browser) ? browser : DEFAULT_LANG;
}

export function formatElapsed(ms: number, lang: Locale): string {
  const s = Math.floor(ms / 1000);
  const m = Math.floor(s / 60);
  const h = Math.floor(m / 60);
  if (h > 0) return t('elapsed.h', lang, { h, m: m % 60 });
  if (m > 0) return t('elapsed.m', lang, { m, s: s % 60 });
  return t('elapsed.s', lang, { s });
}

export function escapeHtml(str: string): string {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
